netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:11 FIN_WAIT2:2 LISTEN:6 TIME_WAIT:2]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:11 FIN_WAIT2:2 LISTEN:7 TIME_WAIT:2]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:4]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[Active:2 Proto:2 tcp:17 tcp6:6 udp:2 udp6:2 unix:141]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:14 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 FIN_WAIT1:1 LISTEN:7 TIME_WAIT:3]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:14 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:388 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[tcp:1 tcp6:1]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:2]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:2]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[root:2]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[tcp:1 tcp6:1]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:3]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:2]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:2]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
session  --  who | awk '{print $1}' | sort | uniq -c  --  map[root:2]
netstat  --  netstat -an | grep tcp | grep -v grep | awk '{print $NF}' | sort | uniq -c  --  map[ESTABLISHED:13 LISTEN:7 TIME_WAIT:1]
process  --  ps aux | grep -v COMMAND | grep -v grep | awk '{print $1}' | sort | uniq -c  --  map[chrony:1 dbus:1 polkitd:1 root:387 zabbix:13]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8f2783]

goroutine 53 [running]:
collect-metrics/handler.(*PrometheusHandler).RunCli(0xc000430d20, {0xb77160, 0x7}, 0xc0000ced20?)
	/home/wangtianci/collect-metrics-with-go/handler/gauge_handler.go:53 +0x123
collect-metrics/handler.(*PrometheusHandler).Gauge.func1.3()
	/home/wangtianci/collect-metrics-with-go/handler/gauge_handler.go:124 +0x70
created by collect-metrics/handler.(*PrometheusHandler).Gauge.func1
	/home/wangtianci/collect-metrics-with-go/handler/gauge_handler.go:119 +0x78a
exit status 2
