---
server:
  listen: 0.0.0.0
  port: 9099
  periodSeconds: 60s

metrics:
  netstat:
    periodSeconds: 36s
    # 获取tcp连接TIME_WAIT数量
    verify_type:
      - "time_wait"
      - "established"
    metric_name: netstat
    metric_help: "get netstat order by state"
  process:
    periodSeconds: 60s
    # 获取各用户进程
    verify_type:
      - "root"
      - "starcross"
    metric_name: "processes"
    metric_help: "get process order by user"

  session:
    periodSeconds: 60s
    # 获取各用户session会话数量
    verify_type:
      - "root"
      - "wtc"
    metric_name: "tty"
    metric_help: "get session order by user"
