---
server:
  listen: 0.0.0.0
  port: 9099
  periodSeconds: 30s
  shutdown_timeout_ms: 1000
  # debug | release, default: debug
  mode: release

metrics:
  # gauage类型指标
  gauge:
    netstat:
      # 扫描频率
      periodSeconds: 15s
    process:
      periodSeconds: 15s
    session:
      periodSeconds: 15s
  histogram:
    delay:
      buckets:
        # 支持切片和线性，若都开启线性优先级高
        linear:
          enabled: True
          range:
            # 边界值: [10 20 30 40 50]
            start: 10
            width: 10
            count: 5
        slice:
          enabled: True
          range:
            # 边界值: [10 20 30 40 50]
            - 10
            - 20
            - 30
            - 40
            - 50
  summary:
    delay:
      median: 
        # 中位数: 度量指标
        10: 10  # example: 采样10%样本，请求小于10ms
        20: 20  # example: 采样20%样本，请求小于20ms
        30: 30  # example: 采样30%样本，请求小于30ms
        40: 40  # example: 采样40%样本，请求小于40ms
        50: 50  # example: 采样50%样本，请求小于50ms