---
server:
  listen: 0.0.0.0
  port: 9099
  periodSeconds: 60s

metrics:
  netstat:
    periodSeconds: 36s
    # 获取tcp连接TIME_WAIT数量
    verify_type:
      - time_wait
      - established
    metric_name:
      - netstat
    metric_labels:
      - "type"
  process:
    periodSeconds: 60s
    # 获取总进程数
    verify_user:
      - "root"
      - "starcross"
    metric_name:
      - "processes"
    metric_labels:
      - "user"
  session:
    periodSeconds: 60
    # 获取ssh session会话数量
    verify_user:
      - "root"
      - "wtc"
    metric_name:
      - "tty"
    metric_labels:
      - "user"