---
server:
  listen: 0.0.0.0
  port: 9099
  global_scrape_interval: 120s

metrics:
  netstat:
    # 获取tcp连接TIME_WAIT数量
    time_wait:
      scrape_interval: 36s
    # 获取tcp连接ESTABLISHED数量
    established:
      scrape_interval: 36s
  process:
    # 获取总进程数
    total_processes:
      scrape_interval: 36s
    # 获取启动用户为starcross的总进程数
    special_user_processes:
      user: starcross
      scrape_interval: 36s
  session:
    # 获取ssh session会话数量
    tty:
      scrape_interval: 36s
    