info:
  contact: {}
paths:
  /test:
    get:
      consumes:
      - application/json
      description: Your endpoint description
      produces:
      - application/json
      responses: {}
      summary: Your endpoint summary
      tags:
      - Your endpoint tags
swagger: "2.0"
